---
title: "Domestication by molars"
author: "Jack Sudds"
date: "27/10/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libaries, include=FALSE}
library(tidyverse)
library(readxl)
library(here)
library(skimr) #install.packages("skimr")
library(kableExtra) #install.packages("kableExtra")
library(formattable)#install.packages("formattable")
library(dplyr)
library(janitor)
library(ggplot2)
library(reshape2)#install.packages("reshape2")
library(RColorBrewer) #install.packages("RColorBrewer")
library(qpcR) #install.packages("qpcR")
```

```{r data import}
dom_molars <- read_excel(here("data", "Domestication 2020.xlsx"), sheet = "Data", range = "A4:M23")

colnames(dom_molars)[1] = "Kebara"
colnames(dom_molars)[2] = "EG III"
colnames(dom_molars)[3] = "Mallaha"
colnames(dom_molars)[4] = "Asiab"
colnames(dom_molars)[5] = "Jarmo"
colnames(dom_molars)[6] = "Hajji Firuz"
colnames(dom_molars)[7] = "Banahilk"
colnames(dom_molars)[8] = "Teleilat Ghassoul"
colnames(dom_molars)[9] = "Korukutepe"
colnames(dom_molars)[10] = "Jammeh Shuran"

dom_molars <- dom_molars %>%
add_column(seq(1, 19, by = 1), .before = "Kebara")

colnames(dom_molars)[1] = "ID"
dom_molars_G <- melt(dom_molars, id.vars = "ID", variable.name = "Site", value.name = "Molar_Length")
```

```{r graphing}

molars_graphing <- ggplot2::ggplot(data = dom_molars_G, aes(x = Site, y = Molar_Length))

molars_graphing +
  geom_point() +
  aes() +
  theme(
        plot.title = element_text(hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(hjust = 0.5),
        panel.background = element_rect(fill = 'white'),
        panel.grid = element_line(color = 'darkgrey'),
        axis.line = element_line(color = 'black'),
        axis.text.x = element_text(angle = 90),
        panel.grid.minor.y = element_blank()
      ) +
  labs(
    y = "Molar Length (mm)"
  ) +
  coord_cartesian(ylim = c(20, 55))+
  scale_y_continuous(breaks = seq(20, 55, by = 5))
  #scale_x_discrete(limits = c())

```

