---
title: "Quantification Exercise"
author: "Jack Sudds"
date: "04/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libaries, include=FALSE}
library(tidyverse)
library(readxl)
library(here)
library(skimr) #install.packages("skimr")
library(kableExtra) #install.packages("kableExtra")
library(formattable)#install.packages("formattable")
library(dplyr)
library(janitor)
library(ggplot2)
library(reshape2)#install.packages("reshape2")
```

```{r dataloda}
horse_messy <- read_xlsx(here("data", "data_as_given.xlsx"), sheet = "Data", range = "B2:D25")

auroch_messy <- read_xlsx(here("data", "data_as_given.xlsx"), sheet = "Data", range = "E2:G25")

red_deer_messy <- read_xlsx(here("data", "data_as_given.xlsx"), sheet = "Data", range = "H2:J25")

rabbit_messy <- read_xlsx(here("data", "data_as_given.xlsx"), sheet = "Data", range = "K2:M25")
```

```{r data-fixing}
nisp_h = sum(horse_messy$Total, na.rm = TRUE)

horse_MNE <- horse_messy %>%
  add_column(read_xlsx(here("data", "data_as_given.xlsx"), sheet = "Data", range = "A2:A25"), .before = "L") %>%
  rename(element = ...1) %>%
  janitor::clean_names() %>%
  add_row(element = "Total NISP", l = NA, r = NA, total = nisp_h) %>%
  remove_rownames() %>%
  column_to_rownames(var = "element")

nisp_a = sum(auroch_messy$Total, na.rm = TRUE)

auroch_MNE <- auroch_messy %>%
  add_column(read_xlsx(here("data", "data_as_given.xlsx"), sheet = "Data", range = "A2:A25"), .before = "L") %>%
  rename(element = ...1) %>%
  janitor::clean_names() %>%
  add_row(element = "Total NISP", l = NA, r = NA, total = nisp_a) %>%
  remove_rownames() %>%
  column_to_rownames(var = "element")

nisp_rd = sum(red_deer_messy$Total, na.rm = TRUE)

red_deer_MNE <- red_deer_messy %>%
  add_column(read_xlsx(here("data", "data_as_given.xlsx"), sheet = "Data", range = "A2:A25"), .before = "L") %>%
  rename(element = ...1) %>%
  janitor::clean_names() %>%
  add_row(element = "Total NISP", l = NA, r = NA, total = nisp_rd) %>%
  remove_rownames() %>%
  column_to_rownames(var = "element")

nisp_r = sum(rabbit_messy$Total, na.rm = TRUE)

rabbit_MNE <- rabbit_messy %>%
  add_column(read_xlsx(here("data", "data_as_given.xlsx"), sheet = "Data", range = "A2:A25"), .before = "L") %>%
  rename(element = ...1) %>%
  janitor::clean_names() %>%
  add_row(element = "Total_NISP", l = NA, r = NA, total = nisp_r) %>%
  remove_rownames() %>%
  column_to_rownames(var = "element")
```

```{r add MAU column horse}

#element MAU calculations horses

mandibleMAU <- as.numeric(horse_MNE[1, 3])/2
maxillaMAU <- as.numeric(horse_MNE[2, 3])/2
atlasMAU <- as.numeric(horse_MNE[3, 3])/1
axisMAU <- as.numeric(horse_MNE[4, 3])/1
scapulaMAU <- as.numeric(horse_MNE[5, 3])/2
p_humerusMAU <- as.numeric(horse_MNE[6, 3])/2
d_humerusMAU <- as.numeric(horse_MNE[7, 3])/2
p_radiusMAU <- as.numeric(horse_MNE[8, 3])/2
d_radiusMAU <- as.numeric(horse_MNE[9, 3])/2
p_metacarpalMAU <- as.numeric(horse_MNE[10, 3])/2
d_metacarpalMAU <- as.numeric(horse_MNE[11, 3])/2
pelvisMAU <- as.numeric(horse_MNE[12, 3])/2
p_femurMAU <- as.numeric(horse_MNE[13, 3])/2
d_femurMAU <- as.numeric(horse_MNE[14, 3])/2
p_tibiaMAU <- as.numeric(horse_MNE[15, 3])/2
d_tibiaMAU <- as.numeric(horse_MNE[16, 3])/2
astragalusMAU <- as.numeric(horse_MNE[17, 3])/2
calcaneumMAU <- as.numeric(horse_MNE[18, 3])/2
p_metatarsalMAU <- as.numeric(horse_MNE[19, 3])/2
d_metatarsalMAU <- as.numeric(horse_MNE[20, 3])/2
phalange1MAU <- as.numeric(horse_MNE[21, 3])/4
phalange2MAU <- as.numeric(horse_MNE[22, 3])/4
phalange3MAU <- as.numeric(horse_MNE[23, 3])/4

MAU_column_h <- c(mandibleMAU, maxillaMAU, atlasMAU, axisMAU, scapulaMAU, p_humerusMAU, d_humerusMAU, p_radiusMAU, d_radiusMAU, p_metacarpalMAU, d_metacarpalMAU, pelvisMAU, p_femurMAU, d_femurMAU, p_tibiaMAU, d_tibiaMAU, astragalusMAU, calcaneumMAU, p_metatarsalMAU, d_metatarsalMAU, phalange1MAU, phalange2MAU, phalange3MAU, NA)

horse_MAU <- horse_MNE %>%
  add_column(.after = "total", MAU = MAU_column_h)

horse_MAU <- horse_MAU %>%
  add_row(.after = "Total NISP", l = NA, r = NA, total = NA, MAU = sum(horse_MAU$MAU, na.rm = TRUE))
  row.names(horse_MAU)[25] <- "Total MAU"
  

```

```{r add MAU column auroch}

#element MAU calculations auroch

mandibleMAU <- as.numeric(auroch_MNE[1, 3])/2
maxillaMAU <- as.numeric(auroch_MNE[2, 3])/2
atlasMAU <- as.numeric(auroch_MNE[3, 3])/1
axisMAU <- as.numeric(auroch_MNE[4, 3])/1
scapulaMAU <- as.numeric(auroch_MNE[5, 3])/2
p_humerusMAU <- as.numeric(auroch_MNE[6, 3])/2
d_humerusMAU <- as.numeric(auroch_MNE[7, 3])/2
p_radiusMAU <- as.numeric(auroch_MNE[8, 3])/2
d_radiusMAU <- as.numeric(auroch_MNE[9, 3])/2
p_metacarpalMAU <- as.numeric(auroch_MNE[10, 3])/2
d_metacarpalMAU <- as.numeric(auroch_MNE[11, 3])/2
pelvisMAU <- as.numeric(auroch_MNE[12, 3])/2
p_femurMAU <- as.numeric(auroch_MNE[13, 3])/2
d_femurMAU <- as.numeric(auroch_MNE[14, 3])/2
p_tibiaMAU <- as.numeric(auroch_MNE[15, 3])/2
d_tibiaMAU <- as.numeric(auroch_MNE[16, 3])/2
astragalusMAU <- as.numeric(auroch_MNE[17, 3])/2
calcaneumMAU <- as.numeric(auroch_MNE[18, 3])/2
p_metatarsalMAU <- as.numeric(auroch_MNE[19, 3])/2
d_metatarsalMAU <- as.numeric(auroch_MNE[20, 3])/2
phalange1MAU <- as.numeric(auroch_MNE[21, 3])/8
phalange2MAU <- as.numeric(auroch_MNE[22, 3])/8
phalange3MAU <- as.numeric(auroch_MNE[23, 3])/8

MAU_column_a <- c(mandibleMAU, maxillaMAU, atlasMAU, axisMAU, scapulaMAU, p_humerusMAU, d_humerusMAU, p_radiusMAU, d_radiusMAU, p_metacarpalMAU, d_metacarpalMAU, pelvisMAU, p_femurMAU, d_femurMAU, p_tibiaMAU, d_tibiaMAU, astragalusMAU, calcaneumMAU, p_metatarsalMAU, d_metatarsalMAU, phalange1MAU, phalange2MAU, phalange3MAU, NA)

auroch_MAU <- auroch_MNE %>%
  add_column(.after = "total", MAU = MAU_column_a)

auroch_MAU <- auroch_MAU%>%
  add_row(.after = "Total NISP", l = NA, r = NA, total = NA, MAU = sum(auroch_MAU$MAU, na.rm = TRUE))
  row.names(auroch_MAU)[25] <- "Total MAU"

```

```{r add MAU column red_deer}

#element MAU calculations red_deer

mandibleMAU <- as.numeric(red_deer_MNE[1, 3])/2
maxillaMAU <- as.numeric(red_deer_MNE[2, 3])/2
atlasMAU <- as.numeric(red_deer_MNE[3, 3])/1
axisMAU <- as.numeric(red_deer_MNE[4, 3])/1
scapulaMAU <- as.numeric(red_deer_MNE[5, 3])/2
p_humerusMAU <- as.numeric(red_deer_MNE[6, 3])/2
d_humerusMAU <- as.numeric(red_deer_MNE[7, 3])/2
p_radiusMAU <- as.numeric(red_deer_MNE[8, 3])/2
d_radiusMAU <- as.numeric(red_deer_MNE[9, 3])/2
p_metacarpalMAU <- as.numeric(red_deer_MNE[10, 3])/2
d_metacarpalMAU <- as.numeric(red_deer_MNE[11, 3])/2
pelvisMAU <- as.numeric(red_deer_MNE[12, 3])/2
p_femurMAU <- as.numeric(red_deer_MNE[13, 3])/2
d_femurMAU <- as.numeric(red_deer_MNE[14, 3])/2
p_tibiaMAU <- as.numeric(red_deer_MNE[15, 3])/2
d_tibiaMAU <- as.numeric(red_deer_MNE[16, 3])/2
astragalusMAU <- as.numeric(red_deer_MNE[17, 3])/2
calcaneumMAU <- as.numeric(red_deer_MNE[18, 3])/2
p_metatarsalMAU <- as.numeric(red_deer_MNE[19, 3])/2
d_metatarsalMAU <- as.numeric(red_deer_MNE[20, 3])/2
phalange1MAU <- as.numeric(red_deer_MNE[21, 3])/8
phalange2MAU <- as.numeric(red_deer_MNE[22, 3])/8
phalange3MAU <- as.numeric(red_deer_MNE[23, 3])/8

MAU_column_rd <- c(mandibleMAU, maxillaMAU, atlasMAU, axisMAU, scapulaMAU, p_humerusMAU, d_humerusMAU, p_radiusMAU, d_radiusMAU, p_metacarpalMAU, d_metacarpalMAU, pelvisMAU, p_femurMAU, d_femurMAU, p_tibiaMAU, d_tibiaMAU, astragalusMAU, calcaneumMAU, p_metatarsalMAU, d_metatarsalMAU, phalange1MAU, phalange2MAU, phalange3MAU, NA)

red_deer_MAU <- red_deer_MNE %>%
  add_column(.after = "total", MAU = MAU_column_rd)

red_deer_MAU <- red_deer_MAU%>%
  add_row(.after = "Total NISP", l = NA, r = NA, total = NA, MAU = sum(red_deer_MAU$MAU, na.rm = TRUE))
  row.names(red_deer_MAU)[25] <- "Total MAU"

```

```{r add MAU column rabbit}

#element MAU calculations rabbit

mandibleMAU <- as.numeric(rabbit_MNE[1, 3])/2
maxillaMAU <- as.numeric(rabbit_MNE[2, 3])/2
atlasMAU <- as.numeric(rabbit_MNE[3, 3])/1
axisMAU <- as.numeric(rabbit_MNE[4, 3])/1
scapulaMAU <- as.numeric(rabbit_MNE[5, 3])/2
p_humerusMAU <- as.numeric(rabbit_MNE[6, 3])/2
d_humerusMAU <- as.numeric(rabbit_MNE[7, 3])/2
p_radiusMAU <- as.numeric(rabbit_MNE[8, 3])/2
d_radiusMAU <- as.numeric(rabbit_MNE[9, 3])/2
p_metacarpalMAU <- as.numeric(rabbit_MNE[10, 3])/8
d_metacarpalMAU <- as.numeric(rabbit_MNE[11, 3])/8
pelvisMAU <- as.numeric(rabbit_MNE[12, 3])/2
p_femurMAU <- as.numeric(rabbit_MNE[13, 3])/2
d_femurMAU <- as.numeric(rabbit_MNE[14, 3])/2
p_tibiaMAU <- as.numeric(rabbit_MNE[15, 3])/2
d_tibiaMAU <- as.numeric(rabbit_MNE[16, 3])/2
astragalusMAU <- as.numeric(rabbit_MNE[17, 3])/2
calcaneumMAU <- as.numeric(rabbit_MNE[18, 3])/2
p_metatarsalMAU <- as.numeric(rabbit_MNE[19, 3])/8
d_metatarsalMAU <- as.numeric(rabbit_MNE[20, 3])/8
phalange1MAU <- as.numeric(rabbit_MNE[21, 3])/16
phalange2MAU <- as.numeric(rabbit_MNE[22, 3])/16
phalange3MAU <- as.numeric(rabbit_MNE[23, 3])/16

MAU_column_r <- c(mandibleMAU, maxillaMAU, atlasMAU, axisMAU, scapulaMAU, p_humerusMAU, d_humerusMAU, p_radiusMAU, d_radiusMAU, p_metacarpalMAU, d_metacarpalMAU, pelvisMAU, p_femurMAU, d_femurMAU, p_tibiaMAU, d_tibiaMAU, astragalusMAU, calcaneumMAU, p_metatarsalMAU, d_metatarsalMAU, phalange1MAU, phalange2MAU, phalange3MAU, NA)

rabbit_MAU <- rabbit_MNE %>%
  add_column(.after = "total", MAU = MAU_column_r)

rabbit_MAU <- rabbit_MAU%>%
  add_row(.after = "Total NISP", l = NA, r = NA, total = NA, MAU = sum(rabbit_MAU$MAU, na.rm = TRUE))
  row.names(rabbit_MAU)[25] <- "Total MAU"

```

```{r MNI calculations horse}

mandibleMNI <- as.numeric(max(horse_MNE[1,1], horse_MNE[1,2], na.rm = TRUE))
maxillaMNI <- as.numeric(max(horse_MNE[2,1], horse_MNE[2,2], na.rm = TRUE))
atlasMNI <- as.numeric(max(horse_MNE[3,1], horse_MNE[3,2], na.rm = TRUE))
axisMNI <- as.numeric(max(horse_MNE[4,1], horse_MNE[4,2], na.rm = TRUE))
scapulaMNI <- as.numeric(max(horse_MNE[5,1], horse_MNE[5,2], na.rm = TRUE))
p_humerusMNI <- as.numeric(max(horse_MNE[6,1], horse_MNE[6,2], na.rm = TRUE))
d_humerusMNI <- as.numeric(max(horse_MNE[7,1], horse_MNE[7,2], na.rm = TRUE))
p_radiusMNI <- as.numeric(max(horse_MNE[8,1], horse_MNE[8,2], na.rm = TRUE))
d_radiusMNI <- as.numeric(max(horse_MNE[9,1], horse_MNE[9,2], na.rm = TRUE))
p_metacarpalMNI <- as.numeric(max(horse_MNE[10,1], horse_MNE[10,2], na.rm = TRUE))
d_metacarpalMNI <- as.numeric(max(horse_MNE[11,1], horse_MNE[11,2], na.rm = TRUE))
pelvisMNI <- as.numeric(max(horse_MNE[12,1], horse_MNE[12,2], na.rm = TRUE))
p_femurMNI <- as.numeric(max(horse_MNE[13,1], horse_MNE[13,2], na.rm = TRUE))
d_femurMNI <- as.numeric(max(horse_MNE[14,1], horse_MNE[14,2], na.rm = TRUE))
p_tibiaMNI <- as.numeric(max(horse_MNE[15,1], horse_MNE[15,2], na.rm = TRUE))
d_tibiaMNI <- as.numeric(max(horse_MNE[16,1], horse_MNE[16,2], na.rm = TRUE))
astragalusMNI <- as.numeric(max(horse_MNE[17,1], horse_MNE[17,2], na.rm = TRUE))
calcaneumMNI <- as.numeric(max(horse_MNE[18,1], horse_MNE[18,2], na.rm = TRUE))
p_metatarsalMNI <- as.numeric(max(horse_MNE[19,1], horse_MNE[19,2], na.rm = TRUE))
d_metatarsalMNI <- as.numeric(max(horse_MNE[20,1], horse_MNE[20,2], na.rm = TRUE))
phalange1MNI <- as.numeric(max(horse_MNE[21,1], horse_MNE[21,2], na.rm = TRUE))/4
phalange2MNI <- as.numeric(max(horse_MNE[22,1], horse_MNE[22,2], na.rm = TRUE))/4
phalange3MNI <- as.numeric(max(horse_MNE[23,1], horse_MNE[23,2], na.rm = TRUE))/4

MNI_column_h <- c(mandibleMNI, maxillaMNI, atlasMNI, axisMNI, scapulaMNI, p_humerusMNI, d_humerusMNI, p_radiusMNI, d_radiusMNI, p_metacarpalMNI, d_metacarpalMNI, pelvisMNI, p_femurMNI, d_femurMNI, p_tibiaMNI, d_tibiaMNI, astragalusMNI, calcaneumMNI, p_metatarsalMNI, d_metatarsalMNI, phalange1MNI, phalange2MNI, phalange3MNI, NA, NA)
                  
MNI_column_h <- MNI_column_h %>%
  na_if(-Inf)

horse_MNI <- horse_MAU %>%
  add_column(.after = "MAU", MNI = MNI_column_h)

horse_MNI <- horse_MNI %>%
  add_row(.after = "Total MAU", l = NA, r = NA, total = NA, MAU = NA, MNI = max(horse_MNI$MNI, na.rm = TRUE))
  row.names(horse_MNI)[26] <- "Total MNI"
  
formattable(horse_MNI)
```

```{r MNI conversion for auroch}

mandibleMNI <- as.numeric(max(auroch_MNE[1,1], auroch_MNE[1,2], na.rm = TRUE))
maxillaMNI <- as.numeric(max(auroch_MNE[2,1], auroch_MNE[2,2], na.rm = TRUE))
atlasMNI <- as.numeric(max(auroch_MNE[3,1], auroch_MNE[3,2], na.rm = TRUE))
axisMNI <- as.numeric(max(auroch_MNE[4,1], auroch_MNE[4,2], na.rm = TRUE))
scapulaMNI <- as.numeric(max(auroch_MNE[5,1], auroch_MNE[5,2], na.rm = TRUE))
p_humerusMNI <- as.numeric(max(auroch_MNE[6,1], auroch_MNE[6,2], na.rm = TRUE))
d_humerusMNI <- as.numeric(max(auroch_MNE[7,1], auroch_MNE[7,2], na.rm = TRUE))
p_radiusMNI <- as.numeric(max(auroch_MNE[8,1], auroch_MNE[8,2], na.rm = TRUE))
d_radiusMNI <- as.numeric(max(auroch_MNE[9,1], auroch_MNE[9,2], na.rm = TRUE))
p_metacarpalMNI <- as.numeric(max(auroch_MNE[10,1], auroch_MNE[10,2], na.rm = TRUE))
d_metacarpalMNI <- as.numeric(max(auroch_MNE[11,1], auroch_MNE[11,2], na.rm = TRUE))
pelvisMNI <- as.numeric(max(auroch_MNE[12,1], auroch_MNE[12,2], na.rm = TRUE))
p_femurMNI <- as.numeric(max(auroch_MNE[13,1], auroch_MNE[13,2], na.rm = TRUE))
d_femurMNI <- as.numeric(max(auroch_MNE[14,1], auroch_MNE[14,2], na.rm = TRUE))
p_tibiaMNI <- as.numeric(max(auroch_MNE[15,1], auroch_MNE[15,2], na.rm = TRUE))
d_tibiaMNI <- as.numeric(max(auroch_MNE[16,1], auroch_MNE[16,2], na.rm = TRUE))
astragalusMNI <- as.numeric(max(auroch_MNE[17,1], auroch_MNE[17,2], na.rm = TRUE))
calcaneumMNI <- as.numeric(max(auroch_MNE[18,1], auroch_MNE[18,2], na.rm = TRUE))
p_metatarsalMNI <- as.numeric(max(auroch_MNE[19,1], auroch_MNE[19,2], na.rm = TRUE))
d_metatarsalMNI <- as.numeric(max(auroch_MNE[20,1], auroch_MNE[20,2], na.rm = TRUE))
phalange1MNI <- as.numeric(max(auroch_MNE[21,1], auroch_MNE[21,2], na.rm = TRUE))/8
phalange2MNI <- as.numeric(max(auroch_MNE[22,1], auroch_MNE[22,2], na.rm = TRUE))/8
phalange3MNI <- as.numeric(max(auroch_MNE[23,1], auroch_MNE[23,2], na.rm = TRUE))/8

MNI_column_a <- c(mandibleMNI, maxillaMNI, atlasMNI, axisMNI, scapulaMNI, p_humerusMNI, d_humerusMNI, p_radiusMNI, d_radiusMNI, p_metacarpalMNI, d_metacarpalMNI, pelvisMNI, p_femurMNI, d_femurMNI, p_tibiaMNI, d_tibiaMNI, astragalusMNI, calcaneumMNI, p_metatarsalMNI, d_metatarsalMNI, phalange1MNI, phalange2MNI, phalange3MNI, NA, NA)
                  
MNI_column_a <- MNI_column_a %>%
  na_if(-Inf)

auroch_MNI <- auroch_MAU %>%
  add_column(.after = "MAU", MNI = MNI_column_a)

auroch_MNI <- auroch_MNI %>%
  add_row(.after = "Total MAU", l = NA, r = NA, total = NA, MAU = NA, MNI = max(auroch_MNI$MNI, na.rm = TRUE))
  row.names(auroch_MNI)[26] <- "Total MNI"

```

```{r MNI conversion for red deer}

mandibleMNI <- as.numeric(max(red_deer_MNE[1,1], red_deer_MNE[1,2], na.rm = TRUE))
maxillaMNI <- as.numeric(max(red_deer_MNE[2,1], red_deer_MNE[2,2], na.rm = TRUE))
atlasMNI <- as.numeric(max(red_deer_MNE[3,1], red_deer_MNE[3,2], na.rm = TRUE))
axisMNI <- as.numeric(max(red_deer_MNE[4,1], red_deer_MNE[4,2], na.rm = TRUE))
scapulaMNI <- as.numeric(max(red_deer_MNE[5,1], red_deer_MNE[5,2], na.rm = TRUE))
p_humerusMNI <- as.numeric(max(red_deer_MNE[6,1], red_deer_MNE[6,2], na.rm = TRUE))
d_humerusMNI <- as.numeric(max(red_deer_MNE[7,1], red_deer_MNE[7,2], na.rm = TRUE))
p_radiusMNI <- as.numeric(max(red_deer_MNE[8,1], red_deer_MNE[8,2], na.rm = TRUE))
d_radiusMNI <- as.numeric(max(red_deer_MNE[9,1], red_deer_MNE[9,2], na.rm = TRUE))
p_metacarpalMNI <- as.numeric(max(red_deer_MNE[10,1], red_deer_MNE[10,2], na.rm = TRUE))
d_metacarpalMNI <- as.numeric(max(red_deer_MNE[11,1], red_deer_MNE[11,2], na.rm = TRUE))
pelvisMNI <- as.numeric(max(red_deer_MNE[12,1], red_deer_MNE[12,2], na.rm = TRUE))
p_femurMNI <- as.numeric(max(red_deer_MNE[13,1], red_deer_MNE[13,2], na.rm = TRUE))
d_femurMNI <- as.numeric(max(red_deer_MNE[14,1], red_deer_MNE[14,2], na.rm = TRUE))
p_tibiaMNI <- as.numeric(max(red_deer_MNE[15,1], red_deer_MNE[15,2], na.rm = TRUE))
d_tibiaMNI <- as.numeric(max(red_deer_MNE[16,1], red_deer_MNE[16,2], na.rm = TRUE))
astragalusMNI <- as.numeric(max(red_deer_MNE[17,1], red_deer_MNE[17,2], na.rm = TRUE))
calcaneumMNI <- as.numeric(max(red_deer_MNE[18,1], red_deer_MNE[18,2], na.rm = TRUE))
p_metatarsalMNI <- as.numeric(max(red_deer_MNE[19,1], red_deer_MNE[19,2], na.rm = TRUE))
d_metatarsalMNI <- as.numeric(max(red_deer_MNE[20,1], red_deer_MNE[20,2], na.rm = TRUE))
phalange1MNI <- as.numeric(max(red_deer_MNE[21,1], red_deer_MNE[21,2], na.rm = TRUE))/8
phalange2MNI <- as.numeric(max(red_deer_MNE[22,1], red_deer_MNE[22,2], na.rm = TRUE))/8
phalange3MNI <- as.numeric(max(red_deer_MNE[23,1], red_deer_MNE[23,2], na.rm = TRUE))/8

MNI_column_rd <- c(mandibleMNI, maxillaMNI, atlasMNI, axisMNI, scapulaMNI, p_humerusMNI, d_humerusMNI, p_radiusMNI, d_radiusMNI, p_metacarpalMNI, d_metacarpalMNI, pelvisMNI, p_femurMNI, d_femurMNI, p_tibiaMNI, d_tibiaMNI, astragalusMNI, calcaneumMNI, p_metatarsalMNI, d_metatarsalMNI, phalange1MNI, phalange2MNI, phalange3MNI, NA, NA)
                  
MNI_column_rd <- MNI_column_rd %>%
  na_if(-Inf)

red_deer_MNI <- red_deer_MAU %>%
  add_column(.after = "MAU", MNI = MNI_column_rd)

red_deer_MNI <- red_deer_MNI %>%
  add_row(.after = "Total MAU", l = NA, r = NA, total = NA, MAU = NA, MNI = max(red_deer_MNI$MNI, na.rm = TRUE))
  row.names(red_deer_MNI)[26] <- "Total MNI"
```

```{r MNI conversions for rabbit}

mandibleMNI <- as.numeric(max(rabbit_MNE[1,1], rabbit_MNE[1,2], na.rm = TRUE))
maxillaMNI <- as.numeric(max(rabbit_MNE[2,1], rabbit_MNE[2,2], na.rm = TRUE))
atlasMNI <- as.numeric(max(rabbit_MNE[3,1], rabbit_MNE[3,2], na.rm = TRUE))
axisMNI <- as.numeric(max(rabbit_MNE[4,1], rabbit_MNE[4,2], na.rm = TRUE))
scapulaMNI <- as.numeric(max(rabbit_MNE[5,1], rabbit_MNE[5,2], na.rm = TRUE))
p_humerusMNI <- as.numeric(max(rabbit_MNE[6,1], rabbit_MNE[6,2], na.rm = TRUE))
d_humerusMNI <- as.numeric(max(rabbit_MNE[7,1], rabbit_MNE[7,2], na.rm = TRUE))
p_radiusMNI <- as.numeric(max(rabbit_MNE[8,1], rabbit_MNE[8,2], na.rm = TRUE))
d_radiusMNI <- as.numeric(max(rabbit_MNE[9,1], rabbit_MNE[9,2], na.rm = TRUE))
p_metacarpalMNI <- as.numeric(max(rabbit_MNE[10,1], rabbit_MNE[10,2], na.rm = TRUE))/4
d_metacarpalMNI <- as.numeric(max(rabbit_MNE[11,1], rabbit_MNE[11,2], na.rm = TRUE))/4
pelvisMNI <- as.numeric(max(rabbit_MNE[12,1], rabbit_MNE[12,2], na.rm = TRUE))
p_femurMNI <- as.numeric(max(rabbit_MNE[13,1], rabbit_MNE[13,2], na.rm = TRUE))
d_femurMNI <- as.numeric(max(rabbit_MNE[14,1], rabbit_MNE[14,2], na.rm = TRUE))
p_tibiaMNI <- as.numeric(max(rabbit_MNE[15,1], rabbit_MNE[15,2], na.rm = TRUE))
d_tibiaMNI <- as.numeric(max(rabbit_MNE[16,1], rabbit_MNE[16,2], na.rm = TRUE))
astragalusMNI <- as.numeric(max(rabbit_MNE[17,1], rabbit_MNE[17,2], na.rm = TRUE))
calcaneumMNI <- as.numeric(max(rabbit_MNE[18,1], rabbit_MNE[18,2], na.rm = TRUE))/2
p_metatarsalMNI <- as.numeric(max(rabbit_MNE[19,1], rabbit_MNE[19,2], na.rm = TRUE))/4
d_metatarsalMNI <- as.numeric(max(rabbit_MNE[20,1], rabbit_MNE[20,2], na.rm = TRUE))/4
phalange1MNI <- as.numeric(max(rabbit_MNE[21,1], rabbit_MNE[21,2], na.rm = TRUE))/16
phalange2MNI <- as.numeric(max(rabbit_MNE[22,1], rabbit_MNE[22,2], na.rm = TRUE))/16
phalange3MNI <- as.numeric(max(rabbit_MNE[23,1], rabbit_MNE[23,2], na.rm = TRUE))/16

MNI_column_r <- c(mandibleMNI, maxillaMNI, atlasMNI, axisMNI, scapulaMNI, p_humerusMNI, d_humerusMNI, p_radiusMNI, d_radiusMNI, p_metacarpalMNI, d_metacarpalMNI, pelvisMNI, p_femurMNI, d_femurMNI, p_tibiaMNI, d_tibiaMNI, astragalusMNI, calcaneumMNI, p_metatarsalMNI, d_metatarsalMNI, phalange1MNI, phalange2MNI, phalange3MNI, NA, NA)
                  
MNI_column_r <- MNI_column_r %>%
  na_if(-Inf)

rabbit_MNI <- rabbit_MAU %>%
  add_column(.after = "MAU", MNI = MNI_column_r)

rabbit_MNI <- rabbit_MNI %>%
  add_row(.after = "Total MAU", l = NA, r = NA, total = NA, MAU = NA, MNI = max(rabbit_MNI$MNI, na.rm = TRUE))
  row.names(rabbit_MNI)[26] <- "Total MNI"
```

```{r NISP proprtions}

options(digits = 2)

NISP_proportion <- data.frame("Taxon" = character(),
                              "NISP" = integer(),
                              "NISP Proportion" = integer(),
                              stringsAsFactors = FALSE)
#set taxa

NISP_proportion <- NISP_proportion %>%
  add_row(Taxon = "Horse") %>%
  add_row(Taxon = "Aurochs") %>%
  add_row(Taxon = "Red Deer") %>%
  add_row(Taxon = "Rabbit") %>%
  add_row(Taxon = "Total NISP")

#import base NISP

NISP_proportion[1,2] = as.numeric(horse_MNE[24,3])
NISP_proportion[2,2] = as.numeric(auroch_MNE[24,3])
NISP_proportion[3,2] = as.numeric(red_deer_MNE[24,3])
NISP_proportion[4,2] = as.numeric(rabbit_MNE[24,3])
NISP_proportion[5,2] = as.numeric(sum(NISP_proportion$NISP, na.rm = TRUE))

#calculate NISP proportions

NISP_proportion[1,3] = as.numeric((NISP_proportion[1,2]/NISP_proportion[5,2])*100)
NISP_proportion[2,3] = as.numeric((NISP_proportion[2,2]/NISP_proportion[5,2])*100)
NISP_proportion[3,3] = as.numeric((NISP_proportion[3,2]/NISP_proportion[5,2])*100)
NISP_proportion[4,3] = as.numeric((NISP_proportion[4,2]/NISP_proportion[5,2])*100)
NISP_proportion[5,3] = as.numeric(sum(NISP_proportion$NISP.Proportion, na.rm = TRUE))
```

```{r MAU Proportions}

options(digits = 2)

MAU_proportion <- data.frame("Taxon" = character(),
                              "MAU" = integer(),
                              "MAU Proportion" = integer(),
                              stringsAsFactors = FALSE)
#set taxa

MAU_proportion <- MAU_proportion %>%
  add_row(Taxon = "Horse") %>%
  add_row(Taxon = "Aurochs") %>%
  add_row(Taxon = "Red Deer") %>%
  add_row(Taxon = "Rabbit") %>%
  add_row(Taxon = "Total MAU")

#import base MAU

MAU_proportion[1,2] = as.numeric(horse_MAU[25,4])
MAU_proportion[2,2] = as.numeric(auroch_MAU[25,4])
MAU_proportion[3,2] = as.numeric(red_deer_MAU[25,4])
MAU_proportion[4,2] = as.numeric(rabbit_MAU[25,4])
MAU_proportion[5,2] = as.numeric(sum(MAU_proportion$MAU, na.rm = TRUE))

#calculate MAU proportions

MAU_proportion[1,3] = as.numeric((MAU_proportion[1,2]/MAU_proportion[5,2])*100)
MAU_proportion[2,3] = as.numeric((MAU_proportion[2,2]/MAU_proportion[5,2])*100)
MAU_proportion[3,3] = as.numeric((MAU_proportion[3,2]/MAU_proportion[5,2])*100)
MAU_proportion[4,3] = as.numeric((MAU_proportion[4,2]/MAU_proportion[5,2])*100)
MAU_proportion[5,3] = as.numeric(sum(MAU_proportion$MAU.Proportion, na.rm = TRUE))
```

```{r MNI Proportion}


options(digits = 2)

MNI_proportion <- data.frame("Taxon" = character(),
                              "MNI" = integer(),
                              "MNI Proportion" = integer(),
                              stringsAsFactors = FALSE)
#set taxa

MNI_proportion <- MNI_proportion %>%
  add_row(Taxon = "Horse") %>%
  add_row(Taxon = "Aurochs") %>%
  add_row(Taxon = "Red Deer") %>%
  add_row(Taxon = "Rabbit") %>%
  add_row(Taxon = "Total MNI")

#import base MNI

MNI_proportion[1,2] = as.numeric(horse_MNI[26,5])
MNI_proportion[2,2] = as.numeric(auroch_MNI[26,5])
MNI_proportion[3,2] = as.numeric(red_deer_MNI[26,5])
MNI_proportion[4,2] = as.numeric(rabbit_MNI[26,5])
MNI_proportion[5,2] = as.numeric(sum(MNI_proportion$MNI, na.rm = TRUE))

#calculate MNI proportions

MNI_proportion[1,3] = as.numeric((MNI_proportion[1,2]/MNI_proportion[5,2])*100)
MNI_proportion[2,3] = as.numeric((MNI_proportion[2,2]/MNI_proportion[5,2])*100)
MNI_proportion[3,3] = as.numeric((MNI_proportion[3,2]/MNI_proportion[5,2])*100)
MNI_proportion[4,3] = as.numeric((MNI_proportion[4,2]/MNI_proportion[5,2])*100)
MNI_proportion[5,3] = as.numeric(sum(MNI_proportion$MNI.Proportion, na.rm = TRUE))
```

```{r meat weight}
options(digits = 2)

Meat_weight <- data.frame("Taxon" = character(),
                              "MNI" = integer(),
                              "Meat Weight kg" = integer(),
                              "Meat Weight Proportion" = integer(),
                              stringsAsFactors = FALSE)

#set taxa

Meat_weight <- Meat_weight %>%
  add_row(Taxon = "Horse") %>%
  add_row(Taxon = "Aurochs") %>%
  add_row(Taxon = "Red Deer") %>%
  add_row(Taxon = "Rabbit") %>%
  add_row(Taxon = "Totals")
  Meat_weight$MNI = MNI_proportion$MNI
  
#calculate meat weights
Meat_weight[1,3] = as.numeric(Meat_weight[1,2]*150) #horse
Meat_weight[2,3] = as.numeric(Meat_weight[2,2]*600) #auroch
Meat_weight[3,3] = as.numeric(Meat_weight[3,2]*75) #red deer
Meat_weight[4,3] = as.numeric(Meat_weight[4,2]*1) #rabbit
Meat_weight[5,3] = as.numeric(sum(Meat_weight$Meat.Weight.kg, na.rm = TRUE))

#Meat weight proportion
Meat_weight[1,4] = as.numeric((Meat_weight[1,2]/Meat_weight[5,2])*100)
Meat_weight[2,4] = as.numeric((Meat_weight[2,2]/Meat_weight[5,2])*100)
Meat_weight[3,4] = as.numeric((Meat_weight[3,2]/Meat_weight[5,2])*100)
Meat_weight[4,4] = as.numeric((Meat_weight[4,2]/Meat_weight[5,2])*100)
Meat_weight[5,4] = as.numeric(sum(Meat_weight$Meat.Weight.Proportion, na.rm = TRUE))

#everyone step to the left
Meat_weight <- Meat_weight %>%
  remove_rownames() %>%
  column_to_rownames(var = "Taxon")
```

```{r proportions table}

all_prop <- data.frame("Taxon" = character(),
                       "NISP" = integer(),
                      "NISP Proportion" = integer(),
                      "MAU" = integer(),
                      "MAU Proportion" = integer(),
                      "MNI" = integer(),
                      "MNI Proportion" = integer(),
                      "Meat Weight kg" = integer(),
                      "Meat Weight Proportion" = integer(),
                      stringsAsFactors = FALSE)

all_prop <- all_prop %>%
  add_row(Taxon = "Horse") %>%
  add_row(Taxon = "Aurochs") %>%
  add_row(Taxon = "Red Deer") %>%
  add_row(Taxon = "Rabbit") %>%
  add_row(Taxon = "Totals")
  all_prop$NISP = NISP_proportion$NISP
  all_prop$NISP.Proportion = NISP_proportion$NISP.Proportion
  all_prop$MAU = MAU_proportion$MAU 
  all_prop$MAU.Proportion = MAU_proportion$MAU.Proportion
  all_prop$MNI = MNI_proportion$MNI 
  all_prop$MNI.Proportion = MNI_proportion$MNI.Proportion
  all_prop$Meat.Weight.kg = Meat_weight$Meat.Weight.kg
  all_prop$Meat.Weight.Proportion = Meat_weight$Meat.Weight.Proportion
```                      


```{r pretty graphs}

all_prop_graphing <- all_prop[-c(5), ]
  
all_prop_graphing <- melt(all_prop_graphing, id.vars = "Taxon", variable.name = "Unit", value.name = "Value")
all_prop_graphing <- all_prop_graphing[complete.cases(all_prop_graphing), ]

ggplot(all_prop_graphing, aes(x = Taxon, y = Value, fill = Unit)) +
  geom_col() +
  theme(
    plot.title = element_text(hjust = 0.5, face = 'bold'),
    panel.background = element_rect(fill = 'white'),
    panel.grid = element_line(color = 'darkgrey'),
    axis.text.x = element_text(angle = 90, vjust = 0.6),
    axis.line = element_line(color = 'black'),
  ) +
  labs(
    x = "Taxon",
    y = "Value",
    title = "Quantitative exercise"
  ) +
  guides(fill = "none") +
  #scale_y_continuous(breaks = c(0, 2, 4, 6, 8, 10, 12), minor_breaks = NULL) +
  facet_wrap(~Unit, scales = "free_y")

ggsave("Quantitative_Exercise_result.png", dpi = 900)

```

```{r Pretty tables}

```

